# Homer - Modern dashboard for all services
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
  namespace: web
data:
  config.yml: |
    ---
    title: "Homelab Dashboard"
    subtitle: "mackie.house"
    logo: "logo.png"
    header: true
    footer: '<p>Homelab Services | <a href="https://status-public.mackie.house">Status Page</a></p>'
    
    theme: default
    colors:
      light:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#f5f5f5"
        card-background: "#ffffff"
        text: "#363636"
        text-header: "#ffffff"
        text-title: "#303030"
        text-subtitle: "#424242"
        card-shadow: rgba(0, 0, 0, 0.1)
        link: "#3273dc"
        link-hover: "#363636"
      dark:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#131313"
        card-background: "#2b2b2b"
        text: "#eaeaea"
        text-header: "#ffffff"
        text-title: "#fafafa"
        text-subtitle: "#f5f5f5"
        card-shadow: rgba(0, 0, 0, 0.4)
        link: "#3273dc"
        link-hover: "#ffdd57"
        
    message:
      style: "is-dark"
      title: "Welcome!"
      icon: "fa fa-grin"
      content: "Homelab services dashboard. Most services require local network access."
      
    links:
      - name: "Documentation"
        icon: "fas fa-book"
        url: "https://github.com/yourusername/homelab"
      - name: "Status Page"
        icon: "fas fa-heartbeat"
        url: "https://status-public.mackie.house"
        
    services:
      - name: "Infrastructure"
        icon: "fas fa-server"
        items:
          - name: "Kubernetes Dashboard"
            logo: "https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png"
            subtitle: "Cluster management"
            tag: "admin"
            url: "https://dashboard.mackie.house"
            target: "_blank"
          - name: "Longhorn"
            logo: "https://longhorn.io/img/logos/longhorn-icon-white.png"
            subtitle: "Storage management"
            tag: "storage"
            url: "https://longhorn.mackie.house"
            target: "_blank"
          - name: "Pi-hole"
            logo: "https://pi-hole.github.io/graphics/Vortex/Vortex_with_text.png"
            subtitle: "DNS & Ad blocking"
            tag: "network"
            url: "https://pihole.mackie.house"
            target: "_blank"
            
      - name: "Monitoring"
        icon: "fas fa-chart-line"
        items:
          - name: "Grafana"
            logo: "https://raw.githubusercontent.com/grafana/grafana/master/public/img/grafana_icon.svg"
            subtitle: "Metrics visualization"
            tag: "monitoring"
            url: "https://grafana.mackie.house"
            target: "_blank"
          - name: "Prometheus"
            logo: "https://raw.githubusercontent.com/prometheus/prometheus/main/documentation/images/prometheus-logo.svg"
            subtitle: "Metrics collection"
            tag: "monitoring"
            url: "https://prometheus.mackie.house"
            target: "_blank"
          - name: "Uptime Kuma"
            subtitle: "Status monitoring"
            tag: "monitoring"
            url: "https://status.mackie.house"
            target: "_blank"
          - name: "Alert Manager"
            subtitle: "Alert routing"
            tag: "monitoring"
            url: "https://alertmanager.mackie.house"
            target: "_blank"
            
      - name: "Media"
        icon: "fas fa-photo-video"
        items:
          - name: "Jellyfin"
            logo: "https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-transparent.svg"
            subtitle: "Media server"
            tag: "media"
            url: "https://jellyfin.mackie.house"
            target: "_blank"
          - name: "Overseerr"
            subtitle: "Request management"
            tag: "public"
            url: "https://requests.mackie.house"
            target: "_blank"
          - name: "Sonarr"
            subtitle: "TV management"
            tag: "media"
            url: "https://sonarr.mackie.house"
            target: "_blank"
          - name: "Radarr"
            subtitle: "Movie management"
            tag: "media"
            url: "https://radarr.mackie.house"
            target: "_blank"
          - name: "Prowlarr"
            subtitle: "Indexer management"
            tag: "media"
            url: "https://prowlarr.mackie.house"
            target: "_blank"
          - name: "SABnzbd"
            subtitle: "Usenet downloader"
            tag: "download"
            url: "https://sabnzbd.mackie.house"
            target: "_blank"
          - name: "Bazarr"
            subtitle: "Subtitle management"
            tag: "media"
            url: "https://bazarr.mackie.house"
            target: "_blank"
            
      - name: "Home Automation"
        icon: "fas fa-home"
        items:
          - name: "Home Assistant"
            logo: "https://raw.githubusercontent.com/home-assistant/assets/master/logo/logo-small.png"
            subtitle: "Smart home platform"
            tag: "automation"
            url: "https://ha.mackie.house"
            target: "_blank"
          - name: "Node-RED"
            logo: "https://nodered.org/about/resources/media/node-red-icon.svg"
            subtitle: "Automation flows"
            tag: "automation"
            url: "https://nodered.mackie.house"
            target: "_blank"
            
      - name: "Tools"
        icon: "fas fa-tools"
        items:
          - name: "Vaultwarden"
            subtitle: "Password manager"
            tag: "security"
            url: "https://vault.mackie.house"
            target: "_blank"
          - name: "Authelia"
            subtitle: "Authentication portal"
            tag: "auth"
            url: "https://auth.mackie.house"
            target: "_blank"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
      - name: homer
        image: b4bz/homer:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /www/assets/config.yml
          subPath: config.yml
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: config
        configMap:
          name: homer-config
---
apiVersion: v1
kind: Service
metadata:
  name: homer
  namespace: web
spec:
  selector:
    app: homer
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homer
  namespace: web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-local-only@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - home.mackie.house
    secretName: homer-tls
  rules:
  - host: home.mackie.house
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homer
            port:
              number: 80