apiVersion: v1
kind: ConfigMap
metadata:
  name: static-site-content
  namespace: web
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>mackie.house</title>
        <style>
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                margin: 0;
                padding: 0;
                background-color: #1a1a1a;
                color: #e0e0e0;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
            }
            .container {
                text-align: center;
                padding: 2rem;
            }
            h1 {
                font-size: 3rem;
                margin-bottom: 1rem;
                color: #4a9eff;
            }
            .links {
                margin-top: 2rem;
            }
            .links a {
                color: #4a9eff;
                text-decoration: none;
                margin: 0 1rem;
                padding: 0.5rem 1rem;
                border: 1px solid #4a9eff;
                border-radius: 4px;
                transition: all 0.3s;
            }
            .links a:hover {
                background-color: #4a9eff;
                color: #1a1a1a;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>mackie.house</h1>
            <p>Welcome to the Homelab</p>
            <div class="links">
                <a href="https://secure.mackie.house">Secure Dashboard</a>
                <a href="https://jellyfin.mackie.house">Media Server</a>
            </div>
            <p style="margin-top: 2rem; font-size: 0.9rem; color: #666;">
                Internal services are only accessible from the local network.
            </p>
        </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: html
        configMap:
          name: static-site-content
---
apiVersion: v1
kind: Service
metadata:
  name: static-site
  namespace: web
spec:
  selector:
    app: static-site
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-site
  namespace: web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - mackie.house
    secretName: mackie-house-tls
  rules:
  - host: mackie.house
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: static-site
            port:
              number: 80