# ArgoCD Application for Monitoring Stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/name: homelab-monitoring
    app.kubernetes.io/part-of: homelab
spec:
  project: homelab-services
  source:
    repoURL: https://github.com/your-org/homelab # Change this!
    targetRevision: HEAD
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m