# ArgoCD Application for Core Services
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-services
  namespace: argocd
  labels:
    app.kubernetes.io/name: homelab-services
    app.kubernetes.io/part-of: homelab
spec:
  project: homelab-services
  source:
    repoURL: https://github.com/your-org/homelab # Change this!
    targetRevision: HEAD
    path: services
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m